/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SonicVisual (https://sketchfab.com/sonicvisual)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/geometry-texture-effect-spheres-5058a0f82e744c27988304db012647d0
title: Geometry Texture Effect Spheres
*/
import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';


export default function Model({ ...props }) {
    

    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/model/scene.gltf');
    const { actions } = useAnimations(animations, group);
    const globalMaterial = new THREE.MeshStandardMaterial({
        color: 0x35133f,
        opacity: 1,
        alphaTest: 0,
        visible: true,
        metalness: 1,
        emissive: 0x000000,
        roughness: 0.4
    });

    // const globalMaterial2 = new THREE.MeshStandardMaterial({
    //     color: 0x454545,
    //     opacity: 1,
    //     alphaTest: 0,
    //     visible: true,
    //     metalness: 1,
    //     emissive: 0x000000,
    //     roughness: 1,
    // });

    const mesh0 = useRef(null);
    const mesh1 = useRef(null);
    const mesh2 = useRef(null);
    const mesh3 = useRef(null);
    const mesh4 = useRef(null);

    useFrame(() => {
        group.current.rotation.y += 0.001;
        console.log()
    });

    return (
        <group {...props} dispose={null}>
            <group>
                <group >
                    <group scale={1}>
                        <group>
                            <group>
                                <group ref={group}  name="Plane" position={[1,0,-1]} rotation={[Math.PI / 4, 0, 0]}>
                                
                                    <mesh
                                        geometry={nodes.Plane_Material001_0.geometry}
                                        material={globalMaterial}
                                        ref={mesh0}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_1.geometry}
                                        material={globalMaterial}
                                        ref={mesh1}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_2.geometry}
                                        material={globalMaterial}
                                        ref={mesh2}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_3.geometry}
                                        material={globalMaterial}
                                        ref={mesh3}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_4.geometry}
                                        material={globalMaterial}
                                        ref={mesh4}
                                    ></mesh>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/model/scene.gltf');
