/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SonicVisual (https://sketchfab.com/sonicvisual)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/geometry-texture-effect-spheres-5058a0f82e744c27988304db012647d0
title: Geometry Texture Effect Spheres
*/
import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ position, rotationSpeed }) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/model/scene.gltf');
    const { actions } = useAnimations(animations, group);
    const globalMaterial = new THREE.MeshStandardMaterial({
        color: 0x35133f,
        opacity: 1,
        alphaTest: 0,
        visible: true,
        metalness: 1,
        emissive: 0x000000,
        roughness: 0.4
    });

    useFrame(() => {
        group.current.rotation.y += rotationSpeed;
    });

    // PAGE 1 position (right) = position={[1,0,-1]}
    // PAGE 2 position (bottom) = position={[0.05,-1.3,-1]}
    // PAGE 3 position (left) = position={[-1.1,0,-1]}

    return (
        <group dispose={null}>
            <group>
                <group >
                    <group scale={1}>
                        <group>
                            <group>
                                <group ref={group}  name="Plane" position={position} rotation={[Math.PI / 4, 0, 0]}>
                                
                                    <mesh
                                        geometry={nodes.Plane_Material001_0.geometry}
                                        material={globalMaterial}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_1.geometry}
                                        material={globalMaterial}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_2.geometry}
                                        material={globalMaterial}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_3.geometry}
                                        material={globalMaterial}
                                    ></mesh>

                                    <mesh
                                        geometry={nodes.Plane_Material001_0_4.geometry}
                                        material={globalMaterial}
                                    ></mesh>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/model/scene.gltf');
